version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./backend:/usr/src/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        API_URL: ${API_URL}
    ports:
      - "5500:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped
